/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carrentalsystem;

import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import java.util.List;
import java.time.LocalDate;

public class BookingManagement extends javax.swing.JFrame {

    static User.admin user;
    DefaultTableModel model;
    final String BOOKING_FILE = dataIO.GET_BOOKING_FILE();
    final String CAR_FILE = dataIO.GET_CAR_FILE();

    public BookingManagement(User.admin user) {
        BookingManagement.user = user;
        initComponents();

        model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        List<Booking> booking = DatabaseManager.getSpecificBookings("Pending", "Cancel");
        populateBookingTable(booking);
        BookingTable.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    int selectedRow = BookingTable.getSelectedRow();
                    if (selectedRow != -1) { 
                        int bookingId = (int) BookingTable.getValueAt(selectedRow, 0);
                        String carName = (String) BookingTable.getValueAt(selectedRow, 1);
                        String userEmail = (String) BookingTable.getValueAt(selectedRow, 2);

                        int rowNumberInBooking = dataIO.rowNumber(bookingId, 1, BOOKING_FILE, 9);

                        LocalDate startDate = LocalDate.parse(dataIO.readData(rowNumberInBooking + 3, BOOKING_FILE));
                        LocalDate endDate = LocalDate.parse(dataIO.readData(rowNumberInBooking + 4, BOOKING_FILE));

                        int days = (int) (endDate.toEpochDay() - startDate.toEpochDay());

                        BookingIdField.setText(String.valueOf(bookingId));
                        CarNameField.setText(carName);
                        UserEmailField.setText(userEmail);
                        StartDateField.setText(startDate.toString());
                        EndDateField.setText(endDate.toString());
                        DurationField.setText(String.valueOf(days) + " days");
                        carPlateField.setText(dataIO.readData(rowNumberInBooking + 7, BOOKING_FILE));

                    }
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        BookingTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        BookingIdField = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        UserEmailField = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CarNameField = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        StartDateField = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        EndDateField = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        DurationField = new javax.swing.JLabel();
        ApproveButton = new javax.swing.JButton();
        RejectButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        carPlateField = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Booking Management");

        BookingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(BookingTable);

        jLabel2.setText("Booking ID:");

        BookingIdField.setText("jLabel3");

        jLabel3.setText("User Email: ");

        UserEmailField.setText(" ");

        jLabel4.setText("Car Booked:");

        CarNameField.setText("jLabel5");

        jLabel5.setText("Start Date: ");

        StartDateField.setText("jLabel6");

        jLabel6.setText("End Date: ");

        EndDateField.setText("jLabel7");

        jLabel7.setText("Duration: ");

        DurationField.setText("jLabel8");

        ApproveButton.setText("Approve");
        ApproveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApproveButtonActionPerformed(evt);
            }
        });

        RejectButton.setText("Reject");
        RejectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RejectButtonActionPerformed(evt);
            }
        });

        jLabel8.setText("Car Plate: ");

        carPlateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carPlateFieldActionPerformed(evt);
            }
        });

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BookingIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(UserEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4)
                                        .addComponent(CarNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(RejectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(124, 124, 124)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ApproveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(StartDateField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(EndDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7)
                                        .addComponent(DurationField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel8)
                            .addComponent(carPlateField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BookingIdField)
                            .addComponent(StartDateField))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(UserEmailField)
                            .addComponent(EndDateField))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CarNameField)
                            .addComponent(DurationField))
                        .addGap(41, 41, 41)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(carPlateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RejectButton)
                            .addComponent(ApproveButton))
                        .addGap(53, 53, 53))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String carPlate; 

    private void RejectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RejectButtonActionPerformed
        if (!BookingIdField.getText().isEmpty()) {
            int rowNumberInBooking = dataIO.rowNumber(BookingIdField.getText(), 1, BOOKING_FILE, 9);
            int rowNumberOfStatus = rowNumberInBooking + 5;
            dataIO.overWriteData("Cancel", rowNumberOfStatus, BOOKING_FILE);
            refreshBookingTable();
        } else {
            JOptionPane.showMessageDialog(null, "Please select a booking to reject.");
        }
    }//GEN-LAST:event_RejectButtonActionPerformed

    private void ApproveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApproveButtonActionPerformed
        carPlateFieldActionPerformed(evt);   
        if (!BookingIdField.getText().isEmpty()) {
            int rowNumberInBooking = dataIO.rowNumber(BookingIdField.getText(), 1, BOOKING_FILE, 9);
            int rowNumberOfStatus = rowNumberInBooking + 5;
            dataIO.overWriteData("Waiting", rowNumberOfStatus, BOOKING_FILE);

            int rowNumberOfCarPlate = rowNumberInBooking + 7;
            dataIO.overWriteData(carPlate, rowNumberOfCarPlate, BOOKING_FILE);
            refreshBookingTable();
        } else {
            JOptionPane.showMessageDialog(null, "Please select a booking to reject.");
        }
    }//GEN-LAST:event_ApproveButtonActionPerformed

    private void carPlateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carPlateFieldActionPerformed
        carPlate = carPlateField.getText();
    }//GEN-LAST:event_carPlateFieldActionPerformed

    private void refreshBookingTable() {
        List<Booking> booking = DatabaseManager.getSpecificBookings("Pending", "Cancel");
        populateBookingTable(booking);
    }

    private void populateBookingTable(List<Booking> bookings) {
        model.setRowCount(0); // Clear existing table data
        model.setColumnCount(0); // Reset column count

        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                // This causes all cells to be non-editable
                return false;
            }
        };
        model.addColumn("Booking ID");
        model.addColumn("Car Name");
        model.addColumn("User Email");
        model.addColumn("Status");
        model.addColumn("Payment Status");
    
        for (Booking booking : bookings) {
            int bookingId = booking.getBookingId();
            String status = booking.getStatus();
            String paymentStatus = booking.getPaymentStatus();

            int rowNumberInBooking = dataIO.rowNumber(bookingId, 1, BOOKING_FILE, 9);

            String carId = dataIO.readData(rowNumberInBooking + 1, BOOKING_FILE); 
            int rowNumberInCar = dataIO.rowNumber(carId, 1, CAR_FILE, 7);

            String carName = dataIO.readData(rowNumberInCar + 1, CAR_FILE);

            String userEmail = dataIO.readData(rowNumberInBooking + 2, BOOKING_FILE); 
    
    
            // Add row to table model with correct role displayed
            model.addRow(new Object[]{bookingId, carName, userEmail, status, paymentStatus});
        }
    
        BookingTable.setModel(model);
    
        // Allow row selection
        BookingTable.setRowSelectionAllowed(true);
    
        // Ensure that cell selection is disabled
        BookingTable.setCellSelectionEnabled(false);
        BookingTable.setColumnSelectionAllowed(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookingManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookingManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookingManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookingManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookingManagement(user).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ApproveButton;
    private javax.swing.JLabel BookingIdField;
    private javax.swing.JTable BookingTable;
    private javax.swing.JLabel CarNameField;
    private javax.swing.JLabel DurationField;
    private javax.swing.JLabel EndDateField;
    private javax.swing.JButton RejectButton;
    private javax.swing.JLabel StartDateField;
    private javax.swing.JLabel UserEmailField;
    private javax.swing.JTextField carPlateField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
